logger:
  level: DEBUG

app:
  timeout: 90

mongo_db:
  connection_url: mongodb+srv://larityai1:YmphRV89c6CxDjkj@cluster0.txarrod.mongodb.net/?retryWrites=true&w=majority
  database: song_lyrics
  collection: song_test

kworb:
  general:
    -  https://kworb.net/youtube/topvideos.html # Most viewed music videos of all time
  youtube_urls:
    Korean: https://kworb.net/youtube/insights/kr.html # korean_youtube
    Spanish:  https://kworb.net/youtube/insights/es.html # spain_youtube
    Hebrew: https://kworb.net/youtube/insights/il.html # israel_youtube

lyrics:
  genius_api_key: Cg8iQ0MxnMUkgqKpRrSHSQCx9lvxaCjv9iNgBpaQvea3N85S4mfPfo9imT3p5AHH